server:
  port: 8089
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: gateway-service
          uri: https://blog.csdn.net/weixin_44782075/article/details/88819901
          order: 0
          predicates:
            - Path=/headers
            - Host=**.foo.org
            - Method=GET
            - Header=X-Request-Id, \d+
            - Query=foo, ba.
            - Query=baz
            - Cookie=chocolate, ch.p
            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]

logging:
  level:
    org.springframework.cloud.gateway: debug
